# Generated by Django 5.2.5 on 2025-11-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_book_title_alter_bookcopy_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
